spring:
  application:
     name: payment_core

server:
  port: 8080

integrations:
  products:
    client:
      rest-template-properties:
        url: "http://127.0.01:8081"
        connect-timeout: 1s
        read-timeout: 3s